export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="size-full" lang="en">
      <body className="size-full bg-gradient-to-t from-blue-200 to-gray-100">{children}</body>
    </html>
  )
}
